apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - redis.yaml
  - configmap.yaml
  - inspectio-api.yaml
  - inspectio-expander.yaml
  - inspectio-worker.yaml
  - inspectio-l1.yaml
