apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-local-s3
  namespace: inspectio
  labels:
    app.kubernetes.io/name: inspectio-exercise
    app.kubernetes.io/component: persistence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
