apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: inspectio
  labels:
    app.kubernetes.io/name: inspectio-exercise
    app.kubernetes.io/component: web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
spec:
  selector:
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: inspectio
  labels:
    app.kubernetes.io/name: inspectio-exercise
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: nginx
          image: inspectio-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: "1"
              memory: 128Mi
